### ISSUE TITLE
ROS2 Bouncy changes namespaces

### ISSUE THREAD

**Issue by jespersmith** [ihmcrobotics/ihmc-java-ros2-communication#1]
According to the change log of Bouncy and observed behaviour, Bouncy does not use partitions anymore for namespaces.

https://github.com/ros2/ros2/wiki/Release-Bouncy-Bolson
```
The ROS topic names containing namespaces are mapped to DDS topics including their namespaces. DDS partitions are not being used anymore for this.
```

I created a PR on stash to change the ROS2 namespace mangler to work with Bouncy
https://stash.ihmc.us/projects/LIBS/repos/ihmc-java-ros2-communication/pull-requests/8/overview

This is a breaking change for Ardent users

**Comment by calvertdw** [comment]
I'm pretty sure I've have been able to communicate both with bouncy and ardent nodes on my machine with this library. I have two questions:

1. What is the error message, or behavior without this change when talking to bouncy?
2. What would be the behavior when talking to ardent with this change?

**Comment by jespersmith** [comment]
Without this change, bouncy does not receive any messages. Bouncy expects no DDS partition, and Ardent requires the namespace prefixed by rt. 

No error messages, you're just on the wrong topic.

Depending on ROS middleware the behaviour could be different.

**Comment by calvertdw** [comment]
Okay, I probably didn't have it working. Do you know why the RTPS visualizer would not pick up my bouncy topics? It can see the ones from Java fine.

**Comment by jespersmith** [comment]
I had no problem seeing the bouncy topics. They are just under "[default domain]"

**Comment by calvertdw** [comment]
Fixed.
