### ISSUE TITLE
Switch throttlerStopwatch to use Throttler

### ISSUE THREAD

**Issue by calvertdw** [ihmcrobotics/ihmc-java-ros2-communication#26]
https://github.com/ihmcrobotics/ihmc-ros2-library/blob/875fa4ed4d7c6eb18dada7fc2bf37d295a7cd009/ros2-library/src/main/java/us/ihmc/ros2/QueuedROS2Publisher.java#L19

**Comment by ds58** [comment]
Fixed in #35
