### ISSUE TITLE
Support Dashing messages

### ISSUE THREAD

**Issue by jespersmith** [ihmcrobotics/ihmc-java-ros2-communication#4]
Currently, the interfaces in ros2-common-interfaces are release 0.4.0, where the latest are 0.7.4 (or dashing).

In ros2-common-interfaces/build.gradle it should be easy to bump this and switch to the newest messages.

**Comment by calvertdw** [comment]
Would be great if you could give this a shot. I'm pretty booked and I don't think it's something we need for any paid work.

**Comment by calvertdw** [comment]
It might also be hard for you to do. I'm not sure if this would require refactoring any code in open-robotics-software
